---
name: Yambs Project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GITHUB_API_TOKEN: ${{secrets.API_TOKEN}}
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.12]

    env:
      PYTHON_VERSION: ${{matrix.python-version}}

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.11.1

      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@main
        with:
          python-version: ${{matrix.python-version}}
          cache: pip

      - run: pip${{matrix.python-version}} install vmklib>=1.8.0 yambs

      - run: mk dz-sync

      - run: mk yaml python-lint python-sa

      # - name: setup clang 17
      #   run: |
      #     wget https://apt.llvm.org/llvm.sh
      #     chmod +x ./llvm.sh
      #     sudo ./llvm.sh 17
      #     rm llvm.sh

      - run: sudo apt-get install gcc-13 g++-13 lcov doxygen clang-17 clang-format-17
      # List versions.
      - run: gcc-13 --version
      - run: g++-13 --version
      - run: clang-17 --version
      - run: clang++-17 --version

      - run: mk t variant=clang coverage=false
      - run: ninja all format-check
      - run: mk dist
        if: github.ref_name != 'master'

      # Need to clean because codecov is not finding coverage otherwise.
      - run: mk c keep=debug
      - run: mk t variant=debug

      - uses: codecov/codecov-action@v3.1.5
        with:
          gcov: true
          gcov_include: build/debug
          gcov_ignore: .mypy_cache
          gcov_executable: gcov-13
          fail_ci_if_error: true
          verbose: true
          token: ${{secrets.CODECOV_TOKEN}}

      - run: mk release
        if: |
          env.GITHUB_API_TOKEN != ''
          && github.ref_name == 'master'
